---
- name: Install Git
  hosts: your_target_hosts
  become: false  # Disable privilege escalation
 
  tasks:
    - name: Install Git
      ansible.builtin.package:
        name: git
        state: present
---
- name: Example Playbook for File Decryption
  hosts: your_target_hosts
  become: yes
  tasks:
    - name: Decrypt File
      ansible.builtin.shell: |
        ansible-vault decrypt /path/to/encrypted_file
      delegate_to: localhost
      changed_when: false
    vars:
      ansible_become_pass: "{{ lookup('tower', 'my_vault_credential_---
- name: Example Playbook for File Decryption
  hosts: your_target_hosts
  become: yes
  tasks:
    - name: Retrieve Vault Password
      set_fact:
        ansible_become_pass: "{{ lookup('tower_credential', 'my_vault_credential_name') }}"
        
    - name: Decrypt File
      ansible.builtin.shell: |
        ansible-vault decrypt /path/to/encrypted_file
      delegate_to: localhost
      changed_when: false
